"""change product price to integer

Revision ID: a00233e6be9f
Revises: b6ba821bf137
Create Date: 2026-10-08 20:23:22.573889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00233e6be9f'
down_revision: Union[str, Sequence[str], None] = 'b6ba821bf137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_user_id_key'), 'orders', type_='unique')
    op.alter_column(
    'products',
    'price',
    existing_type=sa.VARCHAR(),
    type_=sa.Integer(),
    existing_nullable=False,
    postgresql_using='price::integer'
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('orders_user_id_key'), 'orders', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
